server:
  port: 8769
dubbo:
  registry:
    address: zookeeper://zookeeper.t.pinming.org:2181?client=curator
  consumer:
    group: pms_k8s_test04
  provider:
    group: pms_k8s_test04
    host: 172.16.10.205
    threads: 3000
  application:
    name: demo
